### ISSUE TITLE
Choose framework

### ISSUE THREAD

**Issue by ItsEcholot** [hexcodech/booki#1]
Do we want to build the whole stack in Node, or just the Rest API?
If so how would the rest of the stack be built? What MVC is gonna be used?
What features are needed, what needs to be implemented into the framework, what can be added with modules?

[List of available Frameworks](http://nodeframework.com/)

**Comment by Tyratox** [comment]
I'd say we'll only build the REST API in Node as we would be more flexible with the client software on different platforms. (e.g. native apps for iOS, Android, ..) Also I don't really like the idea of an ["Auto-generated UI"](https://allcountjs.com) but that's just my opinion. I think the @hexcodech/design team has to decide on this.

From what I can see I think [Express](http://expressjs.com/) would be worth a try as it's very minimalist but still offers an easy configuration.

**Comment by ItsEcholot** [comment]
I agree, just building the REST API in Node makes a lot of sense tough the @hexcodech/design team should have the final say on this.

Yeah I think Express will bring most things we need to the table and we can easily expand it by using other available modules (e.g. input sanitation & validation).

**Comment by chdabre** [comment]
Easy navigation is key for such a platform to succeed. That requires a streamlined and intuitive interface that really works. I cannot identify how capable Express is but it is very important that we do not have to let the framework decide on how the front end interface operates (because of its features). I recommend we decide on what framework is best when we have a proper idea on how the service will work.

**Comment by ItsEcholot** [comment]
As far as I know the express framework will practically allow us to realize anything we need as it's a pretty slim and basic framework.
I don't see any reasons why this framework should limit and / or obstruct the front end based on that this merely provides a REST API to which all our front ends can connect and make use of.

**Comment by chdabre** [comment]
Sounds great!
