### ISSUE TITLE
Book title on new offer only shows after reload

### ISSUE THREAD

**Issue by chdabre** [hexcodech/booki#11]
After redirecting  to the user profile, the offer shows up green, but without a title, which can cause confusion. On a reload, the title appears.

<img width="594" alt="bildschirmfoto 2017-07-12 um 20 09 05" src="https://user-images.githubusercontent.com/7313617/28132762-12ca91d0-673e-11e7-8b3d-2d822a9f42fd.png">

**Comment by Tyratox** [comment]
Not always, I'm note sure why this sometimes happens as everything loaded in the state. Can someone confirm that the state is correct? (Book with this id is requested & loaded)

Also does this happen for offers, offer-requests or both?

**Comment by chdabre** [comment]
Only happens for offer-requests. Seems to happen on older offers.
